[custom.all.idris-copy]
type = "local"
path = "idris-copy"
ipkg = "idris-copy.ipkg"


[custom.all.idris-mult]
type = "local"
path = "idris-mult"
ipkg = "idris-mult.ipkg"
test = "test/test.ipkg"

[custom.all.idris-mult-test]
type = "local"
path = "test"
ipkg = "test.ipkg"